### ISSUE TITLE
Extra Data of the Blog

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/blog#148]
```yaml
# The main thread of the issue should always in plain YAML
# Feel free to comment on this issue

includedLabelTypes:
  - blog
  - tag
  - series

friends:
  - name: ᴍɪᴍɪ
    blog: https://zhangshuqiao.org/
    avatar: https://avatars3.githubusercontent.com/u/16272760?s=100&v=4
    moto: 做了一点微小的工作

  - name: txtyb
    blog: https://txtyb.github.io/
    avatar: https://avatars2.githubusercontent.com/u/14294192?s=100&v=4
    moto: The quieter you be, the more you can hear.

  - name: Yixuan-Wang
    blog: https://blog.yixuan-wang.site/
    avatar: https://avatars2.githubusercontent.com/u/21151119?s=100&v=4
    moto: "|_| todo!()"

  - name: FX
    blog: https://f-x-chan.github.io/
    avatar: https://avatars.githubusercontent.com/u/35626356?s=100&v=4
    moto: Try adventure time
```
