### ISSUE TITLE
Docker Cheatsheet

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/blog#174]
[View Post on Blog](https://allanchain.github.io/blog/post/docker-cht)

![Docker](https://user-images.githubusercontent.com/36528777/166148769-bd831f8d-eee3-469d-88b0-cd250cee0e16.jpg)

> Docker commands are easily forgotten

---

*Above image from scmagazine.com*

### Cleaning

Remove dangling images
```sh
docker image prune
```
Or remove:
- all stopped containers
- all networks not used by at least one container
- all dangling images
- all dangling build cache
```sh
docker system prune
```

### Updating

Update images managed by Docker compose:

```sh
docker compose pull
docker compose up -d --remove-orphans
```

### Removing
```sh
docker rmi [image name]
docker rm [container name]
```
### Expose Port
```sh
docker run -p [host port]:[container port]
```

### Using Buildx to build image for ARM

```
docker buildx build \
          --tag your-username/multiarch-example:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
```

### Display command output with Buildx

Just add a `--progress=plain` flag.

### Add IPv6

> Disclaimer: may be inaccurate

In `/etc/docker/daemon.json`:

```json
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:3200:1::/64"
}
```

And run:

```sh
sudo systemctl reload docker
```

This reload is graceful so that you don't need to stop containers.

Then in `docker-compose.yml`:

```yaml
services:
  app:
    # ...
    networks:
      - app_net
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1
```
