### ISSUE TITLE
MySQL 存储 emoji | AC's Blog

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/blog#22]
https://allanchain.github.io/blog/programing/2019/MySQL-%E5%AD%98%E5%82%A8-emoji/

**Comment by AllanChain** [comment]
```yaml
SQLALCHEMY_ENGINE_OPTIONS:
    connect_args:
        charset: utf8mb4
        collation: utf8mb4_unicode_ci
```
这里指定编码。
